### ISSUE TITLE
diff of parameters

### ISSUE THREAD

**Issue by herebebogans** [ampedandwired/bora#4]
Sorry for all the feature requests.

It would be really useful for the diff method to show the changes in stack parameters of the current stack vs new.

**Comment by ampedandwired** [comment]
No problem, keep them coming :)

That sounds like a useful feature, should be possible. Do you think it's best implemented as a separate command or as an extension to the existing "diff"?

Also I was thinking of making the diff show only a few lines of context each side of the changes rather than dump the whole template - thoughts?

**Comment by herebebogans** [comment]
I like the idea of a context diff - similar to "git diff" output.

For the parameter diff in the same diff output but with a marker eg

```stack diff
------------------
<stack json context diff>

parameter diff
------------------
<parameters content diff>
```

**Comment by ampedandwired** [comment]
I'm working towards getting this done. Have added a `--context` switch to specify amount of context around the diff (default is 3). Have also added a new command `bora parameters <stack>` which shows you the parameters of any stack. Next step is to get this into the diff.
