### ISSUE TITLE
AMI Resolver?

### ISSUE THREAD

**Issue by herebebogans** [ampedandwired/bora#7]
Would there be interest in an AMI resolver ..?

some ideas for the syntax

> ${ami://OPTIONAL_ACCOUNT_ID/NAME_PREFIX_WILDCARD/}

Lookup latest by creation time

> ${ami://77777777/my_aws_linux*?latest}

Possible lookups by tags / filters

> ${ami://my_aws_linux?state=certified

**Comment by ampedandwired** [comment]
I like it, very useful. Syntax looks good to me. Could be extended with region (although I'm not sure this would be a common requirement): `ami://777777777.ap-southeast-2/my-aws-linux*`

Should "latest" be the default? Otherwise if multiple AMIs match, which one gets returned (or is this an error situation)?

I'd happily accept a PR if you have the time, otherwise I will have a stab at it in the near future.

**Comment by herebebogans** [comment]
I'll have a go at it this week!

**Comment by herebebogans** [comment]
#12

**Comment by ampedandwired** [comment]
Released in version 1.4.0
